### ISSUE TITLE
Documentation for Async Configuration Connection Options

### ISSUE THREAD

**Issue by DavidTheProgrammer** [kpfromer/nestjs-typegoose#12]
I hope this is a good issue, I'm sorry if it is not. I'm struggling to configure the connection options while using the `useFactory` async configuration option. I have tried adding a connection object after returning the uri as shown below
```
TypegooseModule.forRootAsync({
  imports: [ConfigModule],
  useFactory: async (configService: ConfigService) => ({
    uri: configService.MONGO_DB_URI,
    connectionOptions
  }),
  inject: [ConfigService]
})
```
The connectionOptions looks like this: 

```
const connectionOptions: ConnectionOpenOptions = {
  useCreateIndex: true,
  useNewUrlParser: true,
};
```
However even after all this I get the `ensureIndex` and `URL string parser` deprecation warnings. Any assistance would be greatly appreciated

EDIT: After poking around, I've figured it out. The `TypegooseModuleOptions` expects a `uri` key and pairs of key -> value pairs. In essence you're supposed to spread the connection options `...connectionOptions`. The reason I didn't do this initially was because of this code in the `static forRootAsync` method:

```
provide: 'DbConnectionToken',
useFactory: (typegooseModuleOptions: TypegooseModuleOptions) => {
  const {
    uri,
    ...typegooseOptions
  } = typegooseModuleOptions;
```

I thought the options would be automatically be assigned to the `...typegooseOptions` before instantiating the connection. 
Sorry for the inconvenience, you can close this issue.

**Comment by kpfromer** [comment]
I will add some documentation on the async connection options shortly. Thanks for the bringing this up.
