### ISSUE TITLE
How to set timestamp in this library

### ISSUE THREAD

**Issue by ManuRodgers** [kpfromer/nestjs-typegoose#17]
`export const UserModel = new User().getModelForClass(User, { schemaOptions: { timestamps: true } });` this is how to add timestamps in typegoose, but I cannot find the solution in terms of how to add timestamps in this library. so can you guys give me some advice?

**Comment by george-freebirdrides** [comment]
In the event this helps someone else: 

`    TypegooseModule.forFeature(
      { typegooseClass:MyTypegooseClass, schemaOptions: { timestamps: true } })
`
