### ISSUE TITLE
Alternate name for the collection

### ISSUE THREAD

**Issue by recRent** [kpfromer/nestjs-typegoose#2]
Is there a way to pass it an alternate name for the collection.  Mongoose provides the schemaOptions, where you can define an object for an alternate name, which looks like:  { collection: 'category'}.  See below.  How would you give the collection a different name in your implementation?

export const CategorySchema = new Schema({
  name: { type: String, required: true, unique: true },
}, { collection: 'category' });

**Comment by kpfromer** [comment]
Sorry for replying so late, but I just published a new version (5.0.1) that should allow you to add [mongoose schema options for your model](https://github.com/kpfromer/nestjs-typegoose#mongoose-schema-options). If there are any further issues, please let me know!

**Comment by recRent** [comment]
FYI.  Looks like one of your tests might be failing.  There is a snapshot folder in the src, which has the error.

**Comment by kpfromer** [comment]
I think that snapshot is testing for an error message.
