### ISSUE TITLE
v5.2.0 Cannot find module 'nestjs-typegoose'

### ISSUE THREAD

**Issue by duro** [kpfromer/nestjs-typegoose#22]
My CI build is erroring with `Cannot find module 'nestjs-typegoose'`.

I SSH'd into the container doing the build, and when I run `ls -lah` inside the `node_modules/nestjs-typegoose` folder I get this:

```
bash-4.2# ls -lah
total 536K
drwxr-xr-x    3 root root 4.0K Jun  7 00:55 .
drwxr-xr-x 1096 root root  36K Jun  7 00:55 ..
-rw-r--r--    1 root root 3.9K Jun  7 00:55 .npmignore
-rw-r--r--    1 root root  886 Jun  7 00:55 CHANGELOG.md
-rw-r--r--    1 root root 4.2K Jun  7 00:55 CONTRIBUTING.md
-rw-r--r--    1 root root 1.1K Jun  7 00:55 LICENSE
-rw-r--r--    1 root root 6.3K Jun  7 00:55 README.md
-rw-r--r--    1 root root 453K Jun  7 00:55 package-lock.json
-rw-r--r--    1 root root 1.7K Jun  7 00:55 package.json
drwxr-xr-x    2 root root 4.0K Jun  7 00:55 testing-project
-rw-r--r--    1 root root  925 Jun  7 00:55 tslint.json
```

It would appear there is no `dist/index.js`. Did something go wrong in the package and push to NPM?

**Comment by kpfromer** [comment]
I think something went wrong with the continuous integration system. I am going to build manually and push the new version.

**Comment by kpfromer** [comment]
There should be a new version up (`5.2.1`). I will definitely be going through and fixing Travis ci. Thanks for bringing this up.
