### ISSUE TITLE
 No way to save using mongoose-auto-increment

### ISSUE THREAD

**Issue by huazai128** [kpfromer/nestjs-typegoose#27]
import * as mongooseAutoIncrement from 'mongoose-auto-increment'
import { prop, arrayProp, plugin, pre, Typegoose, index } from 'typegoose'

@plugin(mongooseAutoIncrement.plugin, {
  model: Test.name,
  field: 'id',
  startAt: 1,
  incrementBy: 1,
})
export class Test extends Typegoose {
   @IsString()
   @prop({ required: true })
   name: string
}

When saving, this plugin causes the request to continue, neither error nor output

**Comment by kpfromer** [comment]
What do you mean it doesn't error or output, what should be expected? Does the id not increment?

Also, if you could provide an example repo for me to test the issue that would be great?

**Comment by hasezoey** [comment]
@huazai128 this seems like an typegosoe issue and not fully related to nestjs-typegoose, when you still have this problem, please open a new issue at https://github.com/typegoose/typegoose/issues

**Comment by nasr18** [comment]
@hasezoey this is the same issue I'm facing in our project. `mongoose auto increment` plugin using `mongoose.model` method to fetch data. But getting undefined and the plugin keep on trying to connect to that collection.
