### ISSUE TITLE
Support for version 6.

### ISSUE THREAD

**Issue by wxs77577** [kpfromer/nestjs-typegoose#29]
Any plan to support version 6?

https://www.npmjs.com/package/@hasezoey/typegoose

**Comment by NickBolles** [comment]
I was just looking at this. I might put together a PR for v6

**Comment by kpfromer** [comment]
@NickBolles It would be amazing if you could do that. I am quite busy right now with college.

**Comment by wxs77577** [comment]
> I was just looking at this. I might put together a PR for v6

Thanks a lot, and, when will you finish it?

**Comment by kpfromer** [comment]
Fixed with #32 pull request. Thank you @luisvt . The new version is `6.0.0`.
