### ISSUE TITLE
Global schema options

### ISSUE THREAD

**Issue by NickBolles** [kpfromer/nestjs-typegoose#30]
It would be nice to be able to return schema options that will be applied to all models from the .forRoot call. 

For example, If I want timestamps on all of my models I have to pass {timestamps: true} to all of my models. It would be nice If i could just return something like this from .forRoot Options and spread it into each model when calling .forFeature
```
{
  uri: "myUri",
  schemaOptions: {
    timestamps: true
  }
}
```

**Comment by NickBolles** [comment]
I looked at this a little bit, and it's not as simple as just spreading the schema options when .forFeature is called. We would need to make the options passed into .forFeature a provider, which would need to be injected into every model and then spread.

**Comment by kpfromer** [comment]
That sounds promising. Do you have a fork open?

**Comment by NickBolles** [comment]
@kpfromer I don't, and honestly it's a lot easier to just create a utility function that I call to add the options for me. Might be something I look at if I get around to #29 though

```typescript
export function typeGooseOptions(
  typegooseClass: TypegooseClass<any>,
  extraOptions: SchemaOptions = {}
): TypegooseClassWithOptions {
  return {
    typegooseClass,
    schemaOptions: {
      timestamps: true,
      ...extraOptions
    }
  };
}
```

Then use it like this whenever I register a model

```typescript
TypegooseModule.forFeature([typeGooseOptions(User), typeGooseOptions(EmailRecord)])
```

**Comment by hasezoey** [comment]
global model / schema options are planned for typegoose

**Comment by NickBolles** [comment]
Nice! @hasezoey, do you use typegoose with nest?

**Comment by hasezoey** [comment]
> do you use typegoose with nest?

no, i did not use nest & type-graphql yet, but it is a planned feature

**Comment by hasezoey** [comment]
global options are added in 6.1.0-6

@kpfromer this can be closed, when you want to
