### ISSUE TITLE
Techniques for seeding DB

### ISSUE THREAD

**Issue by NickBolles** [kpfromer/nestjs-typegoose#314]
@kpfromer or others. Do you have a suggestion for seeding the DB with test data with Nest and Typegoose? Looking at options right now. I'm using Cypress for testing.

**Comment by kpfromer** [comment]
I personally have not tried this but you could try [this](https://medium.com/the-crowdlinker-chronicle/seeding-databases-using-nestjs-cd6634e8efc5).

**Comment by NickBolles** [comment]
@kpfromer Thanks for the resource! I ended up just doing a test-only controller that uses fakegoose to generate fakes.
