### ISSUE TITLE
Update to @typegooose/typegoose instead of hasezoey/typegoose

### ISSUE THREAD

**Issue by NickBolles** [kpfromer/nestjs-typegoose#33]
@luisvt @kpfromer 

Nice work on migrating to V6 with #32, but we'll probably need to update the package to use `@typegoose/typegoose`, see: https://github.com/typegoose/typegoose/issues/48

Just making this as a reminder for once that package is stable

**Comment by wxs77577** [comment]
The next major version is `6.0`, if you just replace the package name, it still use `v5`, please refer to `v6`:
https://github.com/typegoose/typegoose/tree/r6/master

**Comment by dirkbolte** [comment]
The PR still requires the deprecated functions to be used - but at least it can be used with ```6.0``` of ```@typegoose/typegoose``` . Can we merge this upfront so that we don't block using the new typegoose package?

**Comment by NickBolles** [comment]
@wxs77577 Thanks for the clarification. and @dirkbolte nice PR. With that it should just be a matter of updating the `@typegoose/typegoose` version to 6.0 once it's released.

**Comment by dirkbolte** [comment]
Wasn’t it released yesterday ?

**Comment by duro** [comment]
@dirkbolte I went ahead and whipped up a PR into your fork that upgrades to 6.0 of the @typegoose/typegoose package.

@NickBolles we should all coordinate on what the right release process for this is, since it does have a few breaking changes that are part of the 6.0 migration path.

Here is my PR into @dirkbolte PR:

https://github.com/dirkbolte/nestjs-typegoose/pull/1

**Comment by michaelbats** [comment]
@duro  does your fork have the migration to @typegoose/typegoose added?

**Comment by duro** [comment]
@michaelbats yes it does

**Comment by AmirAlOmari** [comment]
Still looking for it :+1:

**Comment by michaelbats** [comment]
@duro thanks, using that directly from now via github! took a bit of doing switching from extending typegoose to the decorator :)

**Comment by michaelbats** [comment]
@AmirAlOmari  looking for what? a bit confused

**Comment by wxs77577** [comment]
May I ask when to release the latest version?

**Comment by kpfromer** [comment]
The new version is out on `7.0.0`.
