### ISSUE TITLE
Documentation / Dependencies

### ISSUE THREAD

**Issue by fairydhwen** [kpfromer/nestjs-typegoose#4]
Thx for this module, it's realy nice.

Just some questions about the documentation in the section "Cats Service" :

It seems like you use Cat Interface and not Cat Model, is it normal ?
Also we can see a reference to Cats Schema.

In the requierement, you dont list @nestjs/mongoose that you use for the @InjectModel. We dont need to install it ? **[EDIT] => looks like you added "InjectModel" directly inside your module nestjs-typegoose**

Regards

**Comment by fairydhwen** [comment]
BTW what about using something like that for the Cats Service ? 

`import {Injectable} from '@nestjs/common';
import {Cat} from './cat.model';

export class CatsService{

    async create(catName: string): Promise<Cat> {
        const catModel = new Cat().getModelForClass(Cat);
        const createdCat = new catModel({name: catName});
        await createdCat.save();
        return await catModel.findOne();
    }
}`

**Comment by kpfromer** [comment]
Thanks for bringing these issues up! Firstly, I made a typo with the Cat interface and your right; it should be using the Cat model instead. The reason for `InjectModel ` is to prevent repetition of writing `const catModel = new Cat().getModelForClass(Cat)` everytime you use a model in a service. You could of course manually use `getModelForClass` if you wanted. 
I will try to get these changes up later today.
