### ISSUE TITLE
Once destroy module models will not use correct connection

### ISSUE THREAD

**Issue by Goodluckhf** [kpfromer/nestjs-typegoose#41]
Hi! I have an issue the problem I describe in e2e test case:
https://github.com/kpfromer/nestjs-typegoose/pull/40/files#diff-ecad4e9db1639b13ec246bdd84e47d36R90

If you destroy module once, for example invoke `app.close()`. And then create a new one mongoose models will be taken with previous connection. That's cause `typegoose` has singletone cache for that😢.

You can run tests on [this commit with tests](https://github.com/kpfromer/nestjs-typegoose/pull/40/commits/0ac5023ed12a11915fd7e365db49594627146ed6)

I have PR https://github.com/kpfromer/nestjs-typegoose/pull/40

**Comment by hasezoey** [comment]
when i read it correctly, this is a mongoose issue - models are tied to a connection

i currently dont have a link to it, but a search of "model tied connection" or so in the mongoose repo should find something

but i could be completely wrong here ...

**Comment by Goodluckhf** [comment]
Yes you are right, but typegoose store in cache models which had been created before even with connection which has already closed.

https://github.com/typegoose/typegoose/blob/a3f068ed58713adee017c39e21011e934061e987/src/typegoose.ts#L95

**Comment by hasezoey** [comment]
> but typegoose store in cache models which had been created before even with connection which has already closed.

yes you are right - forgot about that

**Comment by Goodluckhf** [comment]
I've created issue https://github.com/typegoose/typegoose/issues/118
So then we can update `typegoose` dependency and use correct version of `.deleteModel`
