### ISSUE TITLE
Error when using newUrlParser

### ISSUE THREAD

**Issue by BurningBubbles** [kpfromer/nestjs-typegoose#47]
I am getting this error when trying to use the newUrlParser. 

CODE:

`@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: 'schema.gql',
    }),
    TypegooseModule.forRoot('mongodb://localhost:27017/nest', { useNewUrlParser:true})
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {
}
`

ERROR:
TS2345: Argument of type '{ useNewUrlParser: boolean; }' is not assignable to parameter of type 'TypegooseConnectionOptions'.
  Object literal may only specify known properties, and 'useNewUrlParser' does not exist in type 'TypegooseConnectionOptions'.

Dependencies: 
"nestjs-typegoose": "^7.0.0",
 "@typegoose/typegoose": "^6.1.2",

**Comment by mikheevm** [comment]
how did you solve this? @BurningBubbles
