### ISSUE TITLE
ModelType

### ISSUE THREAD

**Issue by fairydhwen** [kpfromer/nestjs-typegoose#6]
1) I noticed that i can't get "intellisense" with the injected ModelType<Class> (i.e save() etc.)
When i use typegoose classes directly it works, like u can see on this capture (create method):
![image](https://user-images.githubusercontent.com/3448583/43944954-07ec68be-9c81-11e8-9df1-262c3f505ae7.png)
2) I also added @types/mongoose -dev and after that, i got many errors (cf. same capture).
`The error is : The value of type 'ModelType <Item>' can't be called. Would you like to include "New" ?`
Before that, the code is working without @Type but maybe there is a problem that explains both anomaly ?

**Comment by kpfromer** [comment]
Could you post the typescript type error? Also, aren't you forgetting the `new` keyword in `this.playerModel(createPlayerDto).save`.

**Comment by fairydhwen** [comment]
Oh it's my bad, don't know why i thought the injected class was intanciated. So all is OK sorry ^_^
