### ISSUE TITLE
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

### ISSUE THREAD

**Issue by adikaladik** [kpfromer/nestjs-typegoose#63]
Hi All! 
With current version of this module I cannot specify in the property useUnifiedTopology: true it shows me this argument is not assignable to parameter of type TypegooseConnectionOptions. 
It would be really helpful if someone could help me to resolve this.

**Comment by hasezoey** [comment]
@adikaladik do you have `@types/mongoose` installed? otherwise just use `// @ts-ignore` (ignores the next line)

**Comment by adikaladik** [comment]
@hasezoey yes, I do.

**Comment by hasezoey** [comment]
i dont see any problem doing 
```ts
@Module({
	imports: [
		TypegooseModule.forRoot("mongodb://localhost:27017/somedb",
			{
				useNewUrlParser: true,
				useFindAndModify: false,
				useCreateIndex: true,
				useUnifiedTopology: true, // here
			}),
	],
	exports: [],
	controllers: [],
	providers: []
})
export class AppModule {}
```

**Comment by adikaladik** [comment]
![TypegooseScreen](https://user-images.githubusercontent.com/10028284/73674153-8eaf4780-46b8-11ea-844e-8cd8a060fa70.png)

@hasezoey

**Comment by hasezoey** [comment]
do you use the latest version of nestjs-typegoose?

**Comment by adikaladik** [comment]
"nestjs-typegoose": "^7.0.0",

**Comment by hasezoey** [comment]
could you try:
```sh
npm i -s mongoose @typegoose/typegoose nestjs-typegoose
npm i -D @types/mongoose
```
just to be sure that it is installed and the latest version?

**Comment by kpfromer** [comment]
@adikaladik Did you manage to solve this issue?
