### ISSUE TITLE
About the document

### ISSUE THREAD

**Issue by WumaCoder** [kpfromer/nestjs-typegoose#67]
Is there any more complete documentation, because I would like to know the parameter description of the `options` object of `prop`.

**Comment by hasezoey** [comment]
the mentioned function is not part of this package (nestjs-typegoose), this is only an wrapper plugin for nestjs for [typegoose](https://github.com/typegoose/typegoose), the documentation for typegoose [can be found here](https://typegoose.github.io/typegoose/)
