### ISSUE TITLE
How to use mongoose plugins?

### ISSUE THREAD

**Issue by dzcpy** [kpfromer/nestjs-typegoose#68]

**Comment by dzcpy** [comment]
https://github.com/typegoose/typegoose/blob/65e5e4d72fd4edb955992f2eb27734b9f19882a5/github-page/_docs/decorators/plugins.md

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/docs/decorators/plugins/

**Comment by boskiv** [comment]
Page does not exists anymore. :(

**Comment by hasezoey** [comment]
@boskiv documentaion engine changed, it is now https://typegoose.github.io/typegoose/docs/api/decorators/plugins/
