### ISSUE TITLE
Async configuration

### ISSUE THREAD

**Issue by khashayar** [kpfromer/nestjs-typegoose#7]
The mongoose module for nest/js (`@nestjs/mongoose`) recently introduced the support for async configuration with `MongooseModule.forRootAsync()` method.

https://docs.nestjs.com/techniques/mongodb

Is there any plan here to support the same functionality soon?

**Comment by khashayar** [comment]
Any updates on this?

**Comment by FSM1** [comment]
would also like to know if any progress has been made on this

**Comment by kpfromer** [comment]
Sorry for responding so late. I have been busy with school for the past few months.
I am currently working on it though. Hopefully, I will get it done in the next two weeks.

**Comment by FSM1** [comment]
@kpfromer more than happy to assist with this as well
