### ISSUE TITLE
When I used the `extends` base model, something strange happened.

### ISSUE THREAD

**Issue by guotingchaopr** [kpfromer/nestjs-typegoose#70]
### Base Model

```typescript
 @modelOptions({
  schemaOptions: {
    timestamps: true
  }
})
export abstract class BasicModel {
  _id?: string;

  @prop({
    enum: FIELD_STATUS_ENUM,
    default: FIELD_STATUS_ENUM.USABLE
  })
  public status: FIELD_STATUS_ENUM;

  static get schema(): Schema {
    return buildSchema(this as any, {
      timestamps: true,
      toJSON: {
        getters: true,
        virtuals: true
      }
    });
  }

  static get modelName(): string {
    return this.name;
  }

  get id(): string {
    return this._id;
  }
}
```
### The Feature Model

```typescript
// RoleModel
 @index(
  {
    role_name: 1
  },
  {
    unique: true
  }
)
export class Role extends BasicModel {
  @prop()
  public role_name: string;

  @prop()
  public role_description: string;
}

```

### And Other Feature Model 

```ts
// basicUnitModel
@modelOptions({
  schemaOptions: {
    collection: 'basic_unit',
  },
})
export class BasicUnit extends BasicModel {

  @prop({
    unique: true,
  })
  public unit_name: string;
}
```

--- 
#### Problems 

> When I create a new role using the service

```ts
// role.service.ts
public async createRole(role: Role): Promise<Role> {
    return await this.create(role);
  }
```

> Sometimes, After I restart the app serve, I call the `this.roleService.create (role)` to created the role in roles collection, But it save to  the `basic_uint` collection by mistake.

> This only happens when I use extends BasicModel for RoleModel

**🤔 I think it might be a bug.** 

Can you tell me what is causing this? I don't want to give up `extends` and bypass this problem.

**Comment by kpfromer** [comment]
I think you need to use [monoose discriminators](https://mongoosejs.com/docs/discriminators.html). Object inheritance with [typegoose](https://typegoose.github.io/typegoose/docs/functions/getDiscriminatorModelForClass/) does not carry over all the schema options and properties (this is a limitation with decorators). So you have to use discriminators to tell typegoose to inherit the schema options.

To see how do do this nestjs-typegoose [read here](https://kpfromer.github.io/nestjs-typegoose/docs/discriminators) (note the docs are a work in progress).

**Comment by hasezoey** [comment]
@kpfromer actually when `extends` is used, the modelOptions, indexes, `@prop`'s and theoretically everything should carry over

---

 @guotingchaopr this issue is already known in typegoose and tried fixing it, but it keeps re-appearing, could you list all versions you use?
- nodejs
- typegoose
- nestjs-typegoose
- typescript

**Comment by guotingchaopr** [comment]
> @kpfromer actually when `extends` is used, the modelOptions, indexes, `@prop`'s and theoretically everything should carry over
> 
> @guotingchaopr this issue is already known in typegoose and tried fixing it, but it keeps re-appearing, could you list all versions you use?
> 
> * nodejs
> * typegoose 
> * nestjs-typegoose
> * typescript
> 
> PS: just to make it clear, the issue is about the `Role` model having `basic_units` as collection even though it dosnt extend the model that sets it, right?

#### The version information  follows
- nodejs v12.14.1
- @typegoose/typegoose@^6.2.1 
- nestjs-typegoose@7.0.1
- typescript@3.8.3
- @nestjs/core@6.11.11
- @types/mongoose@5.7.2
- mongodb@v4.2.2


--- 
###  Explain the error

  Sometimes  need to save the role model, 

  **Expected behavior**

>  `roleModel.save()` or `find()`  in  role  -> collection

  **Current behavior**
  
>  `roleModel.save()` or `find()`  in  basic_unit ->  collection

--- 
### The current solution 👻
> I have found a solution now, so far the  mistake has not happened
> I encapsulate a tool method

```ts
  // GeneratorModelOptions.class
import { TypegooseClass, TypegooseClassWithOptions } from 'nestjs-typegoose/dist/typegoose-class.interface';
export const GeneratorModelOptions = (models: TypegooseClass[]): TypegooseClassWithOptions[] => {
  return models.map(
    (model: TypegooseClass): TypegooseClassWithOptions => {
      const forMongCollectionName = model.name.replace(/([A-Z])/g, '_$1').toLowerCase();
      return {
        schemaOptions: {
          collection: forMongCollectionName.slice(1)
        },
        typegooseClass: model
      };
    }
  );
};

  
```

When I need to inject the feature model

```ts
 @Module{
  imports: [TypegooseModule.forFeature(GeneratorModelOptions([Role, RoleAccess]))], 
  ....,
}
```

**Each the feature model, with its own explicit definition of collectionName, There is no problem at present**
