### ISSUE TITLE
Visual Studio Code - Debug Mode Crash

### ISSUE THREAD

**Issue by sguilly** [kpfromer/nestjs-typegoose#78]
Strange issue : the visual studio code debugger code crash when i import TypegooseModule.forRoot

Same issue with a fresh project from "git clone https://github.com/nestjs/typescript-starter.git project" and different node 10 / 11 & 12 and a VSC updated

```
└─ $ ▶  cd /sandbox/project ; env 'DEBUG=app:*' /usr/local/bin/node --nolazy -r ts-node/register --inspect-brk=10800 /sandbox/project/src/main.ts 
Debugger listening on ws://127.0.0.1:10800/0947c54f-0d61-4142-b819-6daf9b54339c
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [/usr/local/bin/node]
 2: 0x1363f0c [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0x13e2801 [/usr/local/bin/node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 6: 0xb43758 [/usr/local/bin/node]
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x33eb1510437d
Abandon
```

```typescript
import * as config from 'config';

import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

import { TypegooseModule } from 'nestjs-typegoose';

const aggregationsWarpUri: string = config.get('mongo.aggregationsWarpUri');


@Module({
  imports: [
    TypegooseModule.forRoot(aggregationsWarpUri, { useNewUrlParser: true, useUnifiedTopology: true, connectionName: 'aggregationsWarpConnection' }),    
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

-------------------------------------- 

**If i comment TypegooseModule.forRoot, i have no issues to start the debugger**

A classic start work well too : npm start

My lunch script for the debugger :

```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
      "type": "node",
      "request": "launch",
      "name": "Debug Nest Framework",
      "args": ["${workspaceFolder}/src/main.ts"],
      "runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "env": {
        "DEBUG": "app:*"
      },
    }]
  }
```

**Comment by kpfromer** [comment]
Hmm. The code you provided it working with me when running the debug script through vs code. I am running node version `v13.11.0`.

**Comment by sguilly** [comment]
By adding ""runtimeExecutable": "/home/toto/.nvm/versions/node/v12.7.0/bin/node" in my launch.json config, the issue is fix.

`
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
    "type": "node",
    "runtimeExecutable": "/home/sguilly/.nvm/versions/node/v12.7.0/bin/node",
    "request": "launch",
    "name": "Debug Nest Framework",
    "args": ["${workspaceFolder}/src/main.ts"],
    "runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
    "sourceMaps": true,
    "cwd": "${workspaceRoot}",
    "protocol": "inspector",
    "console": "integratedTerminal",
    "env": {
      "DEBUG": "app:*"
    },
  }]
}`

Thanks a lot for your project.
